// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: services.proto

package mt5grpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_services_proto protoreflect.FileDescriptor

const file_services_proto_rawDesc = "" +
	"\n" +
	"\x0eservices.proto\x1a\x0emessages.proto\x1a\x1bgoogle/protobuf/empty.proto2\xc4\x10\n" +
	"\x12MetaTrader5Service\x12<\n" +
	"\x0eCopyRatesRange\x12\x16.CopyRatesRangeRequest\x1a\x12.CopyRatesResponse\x12:\n" +
	"\rCopyRatesFrom\x12\x15.CopyRatesFromRequest\x1a\x12.CopyRatesResponse\x12@\n" +
	"\x10CopyRatesFromPos\x12\x18.CopyRatesFromPosRequest\x1a\x12.CopyRatesResponse\x12:\n" +
	"\rCopyTicksFrom\x12\x15.CopyTicksFromRequest\x1a\x12.CopyTicksResponse\x12<\n" +
	"\x0eCopyTicksRange\x12\x16.CopyTicksRangeRequest\x1a\x12.CopyTicksResponse\x125\n" +
	"\n" +
	"SymbolsGet\x12\x12.SymbolsGetRequest\x1a\x13.SymbolsGetResponse\x125\n" +
	"\n" +
	"SymbolInfo\x12\x12.SymbolInfoRequest\x1a\x13.SymbolInfoResponse\x12=\n" +
	"\fSymbolsTotal\x12\x16.google.protobuf.Empty\x1a\x15.SymbolsTotalResponse\x12A\n" +
	"\x0eSymbolInfoTick\x12\x16.SymbolInfoTickRequest\x1a\x17.SymbolInfoTickResponse\x12;\n" +
	"\fSymbolSelect\x12\x14.SymbolSelectRequest\x1a\x15.SymbolSelectResponse\x122\n" +
	"\tOrderSend\x12\x11.OrderSendRequest\x1a\x12.OrderSendResponse\x125\n" +
	"\n" +
	"OrderCheck\x12\x12.OrderCheckRequest\x1a\x13.OrderCheckResponse\x12;\n" +
	"\vOrdersTotal\x12\x16.google.protobuf.Empty\x1a\x14.OrdersTotalResponse\x122\n" +
	"\tOrdersGet\x12\x11.OrdersGetRequest\x1a\x12.OrdersGetResponse\x12D\n" +
	"\x0fOrderCalcMargin\x12\x17.OrderCalcMarginRequest\x1a\x18.OrderCalcMarginResponse\x12D\n" +
	"\x0fOrderCalcProfit\x12\x17.OrderCalcProfitRequest\x1a\x18.OrderCalcProfitResponse\x12;\n" +
	"\fPositionsGet\x12\x14.PositionsGetRequest\x1a\x15.PositionsGetResponse\x12A\n" +
	"\x0ePositionsTotal\x12\x16.google.protobuf.Empty\x1a\x17.PositionsTotalResponse\x12M\n" +
	"\x12HistoryOrdersTotal\x12\x1a.HistoryOrdersTotalRequest\x1a\x1b.HistoryOrdersTotalResponse\x12G\n" +
	"\x10HistoryOrdersGet\x12\x18.HistoryOrdersGetRequest\x1a\x19.HistoryOrdersGetResponse\x12J\n" +
	"\x11HistoryDealsTotal\x12\x19.HistoryDealsTotalRequest\x1a\x1a.HistoryDealsTotalResponse\x12D\n" +
	"\x0fHistoryDealsGet\x12\x17.HistoryDealsGetRequest\x1a\x18.HistoryDealsGetResponse\x127\n" +
	"\tLastError\x12\x16.google.protobuf.Empty\x1a\x12.LastErrorResponse\x12>\n" +
	"\rMarketBookAdd\x12\x15.MarketBookAddRequest\x1a\x16.MarketBookAddResponse\x12>\n" +
	"\rMarketBookGet\x12\x15.MarketBookGetRequest\x1a\x16.MarketBookGetResponse\x12J\n" +
	"\x11MarketBookRelease\x12\x19.MarketBookReleaseRequest\x1a\x1a.MarketBookReleaseResponse\x125\n" +
	"\n" +
	"Initialize\x12\x12.InitializeRequest\x1a\x13.InitializeResponse\x12&\n" +
	"\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponse\x125\n" +
	"\bShutdown\x12\x16.google.protobuf.Empty\x1a\x11.ShutdownResponse\x123\n" +
	"\aVersion\x12\x16.google.protobuf.Empty\x1a\x10.VersionResponse\x12;\n" +
	"\vAccountInfo\x12\x16.google.protobuf.Empty\x1a\x14.AccountInfoResponse\x12=\n" +
	"\fTerminalInfo\x12\x16.google.protobuf.Empty\x1a\x15.TerminalInfoResponse\x12&\n" +
	"\x05Close\x12\r.CloseRequest\x1a\x0e.CloseResponse\x12 \n" +
	"\x03Buy\x12\v.BuyRequest\x1a\f.BuyResponse\x12#\n" +
	"\x04Sell\x12\f.SellRequest\x1a\r.SellResponseBHZFgithub.com/hybrid-syntax/mt5-grpc/go/mt5grpc/generated_proto;mt5grpcpbb\x06proto3"

var file_services_proto_goTypes = []any{
	(*CopyRatesRangeRequest)(nil),      // 0: CopyRatesRangeRequest
	(*CopyRatesFromRequest)(nil),       // 1: CopyRatesFromRequest
	(*CopyRatesFromPosRequest)(nil),    // 2: CopyRatesFromPosRequest
	(*CopyTicksFromRequest)(nil),       // 3: CopyTicksFromRequest
	(*CopyTicksRangeRequest)(nil),      // 4: CopyTicksRangeRequest
	(*SymbolsGetRequest)(nil),          // 5: SymbolsGetRequest
	(*SymbolInfoRequest)(nil),          // 6: SymbolInfoRequest
	(*emptypb.Empty)(nil),              // 7: google.protobuf.Empty
	(*SymbolInfoTickRequest)(nil),      // 8: SymbolInfoTickRequest
	(*SymbolSelectRequest)(nil),        // 9: SymbolSelectRequest
	(*OrderSendRequest)(nil),           // 10: OrderSendRequest
	(*OrderCheckRequest)(nil),          // 11: OrderCheckRequest
	(*OrdersGetRequest)(nil),           // 12: OrdersGetRequest
	(*OrderCalcMarginRequest)(nil),     // 13: OrderCalcMarginRequest
	(*OrderCalcProfitRequest)(nil),     // 14: OrderCalcProfitRequest
	(*PositionsGetRequest)(nil),        // 15: PositionsGetRequest
	(*HistoryOrdersTotalRequest)(nil),  // 16: HistoryOrdersTotalRequest
	(*HistoryOrdersGetRequest)(nil),    // 17: HistoryOrdersGetRequest
	(*HistoryDealsTotalRequest)(nil),   // 18: HistoryDealsTotalRequest
	(*HistoryDealsGetRequest)(nil),     // 19: HistoryDealsGetRequest
	(*MarketBookAddRequest)(nil),       // 20: MarketBookAddRequest
	(*MarketBookGetRequest)(nil),       // 21: MarketBookGetRequest
	(*MarketBookReleaseRequest)(nil),   // 22: MarketBookReleaseRequest
	(*InitializeRequest)(nil),          // 23: InitializeRequest
	(*LoginRequest)(nil),               // 24: LoginRequest
	(*CloseRequest)(nil),               // 25: CloseRequest
	(*BuyRequest)(nil),                 // 26: BuyRequest
	(*SellRequest)(nil),                // 27: SellRequest
	(*CopyRatesResponse)(nil),          // 28: CopyRatesResponse
	(*CopyTicksResponse)(nil),          // 29: CopyTicksResponse
	(*SymbolsGetResponse)(nil),         // 30: SymbolsGetResponse
	(*SymbolInfoResponse)(nil),         // 31: SymbolInfoResponse
	(*SymbolsTotalResponse)(nil),       // 32: SymbolsTotalResponse
	(*SymbolInfoTickResponse)(nil),     // 33: SymbolInfoTickResponse
	(*SymbolSelectResponse)(nil),       // 34: SymbolSelectResponse
	(*OrderSendResponse)(nil),          // 35: OrderSendResponse
	(*OrderCheckResponse)(nil),         // 36: OrderCheckResponse
	(*OrdersTotalResponse)(nil),        // 37: OrdersTotalResponse
	(*OrdersGetResponse)(nil),          // 38: OrdersGetResponse
	(*OrderCalcMarginResponse)(nil),    // 39: OrderCalcMarginResponse
	(*OrderCalcProfitResponse)(nil),    // 40: OrderCalcProfitResponse
	(*PositionsGetResponse)(nil),       // 41: PositionsGetResponse
	(*PositionsTotalResponse)(nil),     // 42: PositionsTotalResponse
	(*HistoryOrdersTotalResponse)(nil), // 43: HistoryOrdersTotalResponse
	(*HistoryOrdersGetResponse)(nil),   // 44: HistoryOrdersGetResponse
	(*HistoryDealsTotalResponse)(nil),  // 45: HistoryDealsTotalResponse
	(*HistoryDealsGetResponse)(nil),    // 46: HistoryDealsGetResponse
	(*LastErrorResponse)(nil),          // 47: LastErrorResponse
	(*MarketBookAddResponse)(nil),      // 48: MarketBookAddResponse
	(*MarketBookGetResponse)(nil),      // 49: MarketBookGetResponse
	(*MarketBookReleaseResponse)(nil),  // 50: MarketBookReleaseResponse
	(*InitializeResponse)(nil),         // 51: InitializeResponse
	(*LoginResponse)(nil),              // 52: LoginResponse
	(*ShutdownResponse)(nil),           // 53: ShutdownResponse
	(*VersionResponse)(nil),            // 54: VersionResponse
	(*AccountInfoResponse)(nil),        // 55: AccountInfoResponse
	(*TerminalInfoResponse)(nil),       // 56: TerminalInfoResponse
	(*CloseResponse)(nil),              // 57: CloseResponse
	(*BuyResponse)(nil),                // 58: BuyResponse
	(*SellResponse)(nil),               // 59: SellResponse
}
var file_services_proto_depIdxs = []int32{
	0,  // 0: MetaTrader5Service.CopyRatesRange:input_type -> CopyRatesRangeRequest
	1,  // 1: MetaTrader5Service.CopyRatesFrom:input_type -> CopyRatesFromRequest
	2,  // 2: MetaTrader5Service.CopyRatesFromPos:input_type -> CopyRatesFromPosRequest
	3,  // 3: MetaTrader5Service.CopyTicksFrom:input_type -> CopyTicksFromRequest
	4,  // 4: MetaTrader5Service.CopyTicksRange:input_type -> CopyTicksRangeRequest
	5,  // 5: MetaTrader5Service.SymbolsGet:input_type -> SymbolsGetRequest
	6,  // 6: MetaTrader5Service.SymbolInfo:input_type -> SymbolInfoRequest
	7,  // 7: MetaTrader5Service.SymbolsTotal:input_type -> google.protobuf.Empty
	8,  // 8: MetaTrader5Service.SymbolInfoTick:input_type -> SymbolInfoTickRequest
	9,  // 9: MetaTrader5Service.SymbolSelect:input_type -> SymbolSelectRequest
	10, // 10: MetaTrader5Service.OrderSend:input_type -> OrderSendRequest
	11, // 11: MetaTrader5Service.OrderCheck:input_type -> OrderCheckRequest
	7,  // 12: MetaTrader5Service.OrdersTotal:input_type -> google.protobuf.Empty
	12, // 13: MetaTrader5Service.OrdersGet:input_type -> OrdersGetRequest
	13, // 14: MetaTrader5Service.OrderCalcMargin:input_type -> OrderCalcMarginRequest
	14, // 15: MetaTrader5Service.OrderCalcProfit:input_type -> OrderCalcProfitRequest
	15, // 16: MetaTrader5Service.PositionsGet:input_type -> PositionsGetRequest
	7,  // 17: MetaTrader5Service.PositionsTotal:input_type -> google.protobuf.Empty
	16, // 18: MetaTrader5Service.HistoryOrdersTotal:input_type -> HistoryOrdersTotalRequest
	17, // 19: MetaTrader5Service.HistoryOrdersGet:input_type -> HistoryOrdersGetRequest
	18, // 20: MetaTrader5Service.HistoryDealsTotal:input_type -> HistoryDealsTotalRequest
	19, // 21: MetaTrader5Service.HistoryDealsGet:input_type -> HistoryDealsGetRequest
	7,  // 22: MetaTrader5Service.LastError:input_type -> google.protobuf.Empty
	20, // 23: MetaTrader5Service.MarketBookAdd:input_type -> MarketBookAddRequest
	21, // 24: MetaTrader5Service.MarketBookGet:input_type -> MarketBookGetRequest
	22, // 25: MetaTrader5Service.MarketBookRelease:input_type -> MarketBookReleaseRequest
	23, // 26: MetaTrader5Service.Initialize:input_type -> InitializeRequest
	24, // 27: MetaTrader5Service.Login:input_type -> LoginRequest
	7,  // 28: MetaTrader5Service.Shutdown:input_type -> google.protobuf.Empty
	7,  // 29: MetaTrader5Service.Version:input_type -> google.protobuf.Empty
	7,  // 30: MetaTrader5Service.AccountInfo:input_type -> google.protobuf.Empty
	7,  // 31: MetaTrader5Service.TerminalInfo:input_type -> google.protobuf.Empty
	25, // 32: MetaTrader5Service.Close:input_type -> CloseRequest
	26, // 33: MetaTrader5Service.Buy:input_type -> BuyRequest
	27, // 34: MetaTrader5Service.Sell:input_type -> SellRequest
	28, // 35: MetaTrader5Service.CopyRatesRange:output_type -> CopyRatesResponse
	28, // 36: MetaTrader5Service.CopyRatesFrom:output_type -> CopyRatesResponse
	28, // 37: MetaTrader5Service.CopyRatesFromPos:output_type -> CopyRatesResponse
	29, // 38: MetaTrader5Service.CopyTicksFrom:output_type -> CopyTicksResponse
	29, // 39: MetaTrader5Service.CopyTicksRange:output_type -> CopyTicksResponse
	30, // 40: MetaTrader5Service.SymbolsGet:output_type -> SymbolsGetResponse
	31, // 41: MetaTrader5Service.SymbolInfo:output_type -> SymbolInfoResponse
	32, // 42: MetaTrader5Service.SymbolsTotal:output_type -> SymbolsTotalResponse
	33, // 43: MetaTrader5Service.SymbolInfoTick:output_type -> SymbolInfoTickResponse
	34, // 44: MetaTrader5Service.SymbolSelect:output_type -> SymbolSelectResponse
	35, // 45: MetaTrader5Service.OrderSend:output_type -> OrderSendResponse
	36, // 46: MetaTrader5Service.OrderCheck:output_type -> OrderCheckResponse
	37, // 47: MetaTrader5Service.OrdersTotal:output_type -> OrdersTotalResponse
	38, // 48: MetaTrader5Service.OrdersGet:output_type -> OrdersGetResponse
	39, // 49: MetaTrader5Service.OrderCalcMargin:output_type -> OrderCalcMarginResponse
	40, // 50: MetaTrader5Service.OrderCalcProfit:output_type -> OrderCalcProfitResponse
	41, // 51: MetaTrader5Service.PositionsGet:output_type -> PositionsGetResponse
	42, // 52: MetaTrader5Service.PositionsTotal:output_type -> PositionsTotalResponse
	43, // 53: MetaTrader5Service.HistoryOrdersTotal:output_type -> HistoryOrdersTotalResponse
	44, // 54: MetaTrader5Service.HistoryOrdersGet:output_type -> HistoryOrdersGetResponse
	45, // 55: MetaTrader5Service.HistoryDealsTotal:output_type -> HistoryDealsTotalResponse
	46, // 56: MetaTrader5Service.HistoryDealsGet:output_type -> HistoryDealsGetResponse
	47, // 57: MetaTrader5Service.LastError:output_type -> LastErrorResponse
	48, // 58: MetaTrader5Service.MarketBookAdd:output_type -> MarketBookAddResponse
	49, // 59: MetaTrader5Service.MarketBookGet:output_type -> MarketBookGetResponse
	50, // 60: MetaTrader5Service.MarketBookRelease:output_type -> MarketBookReleaseResponse
	51, // 61: MetaTrader5Service.Initialize:output_type -> InitializeResponse
	52, // 62: MetaTrader5Service.Login:output_type -> LoginResponse
	53, // 63: MetaTrader5Service.Shutdown:output_type -> ShutdownResponse
	54, // 64: MetaTrader5Service.Version:output_type -> VersionResponse
	55, // 65: MetaTrader5Service.AccountInfo:output_type -> AccountInfoResponse
	56, // 66: MetaTrader5Service.TerminalInfo:output_type -> TerminalInfoResponse
	57, // 67: MetaTrader5Service.Close:output_type -> CloseResponse
	58, // 68: MetaTrader5Service.Buy:output_type -> BuyResponse
	59, // 69: MetaTrader5Service.Sell:output_type -> SellResponse
	35, // [35:70] is the sub-list for method output_type
	0,  // [0:35] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_services_proto_init() }
func file_services_proto_init() {
	if File_services_proto != nil {
		return
	}
	file_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_proto_rawDesc), len(file_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_proto_goTypes,
		DependencyIndexes: file_services_proto_depIdxs,
	}.Build()
	File_services_proto = out.File
	file_services_proto_goTypes = nil
	file_services_proto_depIdxs = nil
}
